// error handling

try {
    console.log(a)
} catch (error) {
    console.log("something went wrong");
}